### ISSUE TITLE
Sub::Exporter no longer installs on perl 5.10 because of Data::OptList

### ISSUE THREAD

**Issue by damil** [rjbs/Sub-Exporter#16]
The latest version of Data::OptList requires perl 5.12, so the minimal version for Sub::Exporter should also declare 5.12 ... or find an alternative implementation for older perls.

**Comment by damil** [comment]
(forgot to say : Data::Domain depends on Sub::Exporter, so I'm forced to also put 5.12 as minimal version  .. this is a bit unfortunate)

**Comment by damil** [comment]
Moose also depends on Sub::Exporter and therefore can no longer install on 5.10

**Comment by rjbs** [comment]
The install toolchain itself has declared that v5.20 is an okay minimum starting in July, and v5.16 now.  Perl v5.12.0 is over thirteen years old now.  I am pretty freely letting myself rely on perls at _least_ that recent, and v5.20 is probably likely in future releases.

I will make the v5.12 requirement in Sub-Exporter explicit in the next release.
