### ISSUE TITLE
Failing test on perl 5.39.1

### ISSUE THREAD

**Issue by mauke** [rjbs/Sub-Exporter#18]
Starting with 5.39.1, tests are failing:

> Attempt to call undefined import method with arguments via package "Test::SubExporter::SETUPALT" (Perhaps you forgot to load the package?) at t/real-export-setup.t line 149.

This is because `import` is no longer special-cased by the interpreter. It is looked up as a normal method in `UNIVERSAL`, and `UNIVERSAL::import` dies if passed arguments.

**Comment by rjbs** [comment]
This will be fixed by #17

**Comment by rjbs** [comment]
Should be fixed in new release.
